browser=chrome

baseUrl=https://practice.expandtesting.com/notes/app/login
apiBaseUrl=https://practice.expandtesting.com/notes/api

email=gaurinagolkar@gmail.com
password=Gauri@123

explicitWait=15
api.response.threshold=10000