baseUrl=https://practice.expandtesting.com/notes/app
apiBaseUrl=https://practice.expandtesting.com/notes/api

email=testuser123@gmail.com
password=Test@123

browser=chrome

implicitWait=10
explicitWait=20